### ISSUE TITLE
Bug: rtl problem

### ISSUE THREAD

**Issue by naftali100** [maormagori/ktuvit-stremio#51]
the "." and "!" in end of line are in the wrong place

![image](https://github.com/maormagori/ktuvit-stremio/assets/48069590/2f55f4b6-a84f-4b54-a99c-f9a8da56fabb)

**Comment by maormagori** [comment]
Hey @naftali100 ,
This is actually a problem with your media player 😅

This issue is well known in every media player. 
Those characters are assigned the LTR ordering even though the rest of sentence is in an RTL language. After all, the media player's RTL implementation ends with supporting RTL characters. Deciphering the entire sentence's ordering and placing the universal characters at the relevant end will require extra attention from those media player's developers and gets looked over most of the time.


My suggestion is this,
At the moment you should try experimenting with different media players ( VLC will most likely work), and I'll change this issue to a feature request where the feature is exporting two sets of subtitles. One where those characters are flipped, and the usual one that's already being exported. That way I won't break any working setups. 

Let me know wdyt.

**Comment by naftali100** [comment]
Actually, i noticed that i only happens with subtitles from the openSubtitles extension, and the ktuvit one is working fine, thanks
