### ISSUE TITLE
Addon subtitle to video file name matching

### ISSUE THREAD

**Issue by TwilightMercy** [maormagori/ktuvit-stremio#54]
Hi,

It has been almost a year since your issue to Stremio:
https://github.com/Stremio/stremio-addon-sdk/issues/221

I've wanted to know if this situation is still the same (filename is not present in [Extra Paraemeters](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/requests/defineSubtitlesHandler.md#extra-parameters)), or do you know if something has changed since then?

https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md

If not, then subtitles from Ktuvit/Wizdom addon are sorted in a different order than by matching to video file name?

Thank you!

**Comment by maormagori** [comment]
Hey @TwilightMercy !
The Stremio devs haven't updated anything on their documentation so we can't really tell if anything changed for better or worse.
 Since the last time this happened, the docs claimed one thing and in reality, something else was happening, we can't really know the situation until we check for ourselves.
Last time I had to resort to sniffing the packets from each client to find the difference between requests.
Let's hope we won't have to do that this time.


Either way, the logic to sort the subtitles by filenames is still present. If we get the filename then it works as expected, if not, well the user receives back an unordered list of subs.

**Comment by TwilightMercy** [comment]
Great to hear!
